// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuR9uf7sz5VYYpG5j7vNTqoVLpjDHhgMA',
    appId: '1:80640900084:web:448d526ebca8769e2297a1',
    messagingSenderId: '80640900084',
    projectId: 'ice-cream-shop-5e9da',
    authDomain: 'ice-cream-shop-5e9da.firebaseapp.com',
    storageBucket: 'ice-cream-shop-5e9da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF7iSw_E5899VOrzgMrhqYUbMignyUbCs',
    appId: '1:80640900084:android:97cf103b036f201b2297a1',
    messagingSenderId: '80640900084',
    projectId: 'ice-cream-shop-5e9da',
    storageBucket: 'ice-cream-shop-5e9da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADBccG9DFr3jMrS89LkJ_b0wnCHIzfVjk',
    appId: '1:80640900084:ios:a2c46d2d0902fa982297a1',
    messagingSenderId: '80640900084',
    projectId: 'ice-cream-shop-5e9da',
    storageBucket: 'ice-cream-shop-5e9da.firebasestorage.app',
    iosBundleId: 'com.example.iceCreamShopAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADBccG9DFr3jMrS89LkJ_b0wnCHIzfVjk',
    appId: '1:80640900084:ios:a2c46d2d0902fa982297a1',
    messagingSenderId: '80640900084',
    projectId: 'ice-cream-shop-5e9da',
    storageBucket: 'ice-cream-shop-5e9da.firebasestorage.app',
    iosBundleId: 'com.example.iceCreamShopAdmin',
  );
}
